# Generated by Django 4.0.6 on 2022-11-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameuser', models.CharField(max_length=100)),
                ('emailuser', models.EmailField(max_length=100)),
                ('password_one', models.CharField(max_length=100)),
            ],
        ),
    ]
